<?php

namespace AppBundle\Repository;

/**
 * InternautRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InternautRepository extends \Doctrine\ORM\EntityRepository
{
}
