<?php

namespace AppBundle\Repository;

/**
 * PostCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCodeRepository extends \Doctrine\ORM\EntityRepository
{
    public function createNumericOrderQueryBuilder(){
        $qb = $this->createQueryBuilder('postCode');

        $qb
            ->orderBy('postCode.postCode', 'ASC');

        return $qb
            ;
    }

}
