<?php

namespace AppBundle\Repository;

/**
 * PostCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
