<?php

namespace AppBundle\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
//    public function getPromotionsWithProvider($provider)
//    {
//        $qb = $this
//            ->createQueryBuilder('prom')
//            ->leftJoin('prom.provider', 'prov')
//            ->addSelect('prov')
//            ->where('prov.')
//
//        ;
//
//        return $qb
//            ->getQuery()
//            ->getResult();
//    }
}
