<?php

namespace AppBundle\Repository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProvider($name, $postCode, $categorie){

        $qb = $this->createQueryBuilder('p');

        if($name != '')
        {
            $qb->andWhere('p.name = :name')
                ->setParameter('name',$name);
        }
        if($postCode != '')
        {
            $qb->andWhere('p.postCode = :postCode')
                ->setParameter('postCode',$postCode);
        }
        if($categorie != '')
        {
            $qb->andWhere('p.serviceCategories = :serviceCategories')
                ->setParameter('serviceCategories', $categorie);
        }

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
//    public function findProviders($data)
//
//    {
//
//        $query = $this->createQueryBuilder('p');
//
//        $query
//            ->where('a.anneeProduction BETWEEN :anneeProductionMin AND :anneeProductionMax')
//
//            ->andWhere('a.kilometres BETWEEN :kilometresMin AND :kilometresMax')
//
//            ->andWhere('a.prix BETWEEN :prixMin AND :prixMax')
//
//            ->setParameters(array(
//
//                'anneeProductionMin' => $data['annee_Production'],
//
//                'anneeProductionMax' => $data['annee_Production_Max'],
//
//                'kilometresMin' => $data['kilometres'],
//
//                'kilometresMax' => $data['kilometres_Max'],
//
//                'prixMin' => $data['prix'],
//
//                'prixMax' => $data['prix_Max']));
//
//
//
//        return $query->getQuery()->getResult();
//
//    }

}
