<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends EntityRepository
{

    public function findAllNotBannedOrderedByName(){

        $qb = $this->createQueryBuilder('provider');

            $qb
                ->where('provider.banned = :banned')
                ->setParameter('banned',false)
                ->orderBy('provider.name', 'ASC')
            ;

            return $qb
                ->getQuery()
                ->getResult();

    }

    public function findOneBySlug($slug){

        $qb = $this->createQueryBuilder('provider');

            $qb
                ->where('provider.slug = :slug')
                ->setParameter('slug',$slug)
            ;

            return $qb
                ->getQuery()
                ->getSingleResult();

    }



    public function findProvider($name, $postCode, $categorie){

        $qb = $this->createQueryBuilder('p');

        if($name != '')
        {
            $qb->andWhere('p.name LIKE :name')
                ->setParameter('name','%'.$name.'%');
        }
        if($postCode != '')
        {
            $qb
                ->leftJoin('p.postCode','pc')
                ->addSelect('pc')
                ->andWhere('pc.postCode = :postCode')
                ->setParameter('postCode',$postCode);
        }
        if($categorie != '')
        {
            $qb
                ->leftJoin('p.serviceCategories', 'sc')
                ->addSelect('sc')
                ->andWhere('sc.id = :serviceCategories')
                ->setParameter('serviceCategories', $categorie)
            ;
        }

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

}
