<?php

namespace AppBundle\Repository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProvider($data){

        $qb = $this->createQueryBuilder('p');

        $qb
            ->where('p.serviceCategories = :serviceCategories')
            ->setParameter(
            'serviceCategories', $data['service_Categories']
            );

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
//    public function findProviders($data)
//
//    {
//
//        $query = $this->createQueryBuilder('p');
//
//        $query
//            ->where('a.anneeProduction BETWEEN :anneeProductionMin AND :anneeProductionMax')
//
//            ->andWhere('a.kilometres BETWEEN :kilometresMin AND :kilometresMax')
//
//            ->andWhere('a.prix BETWEEN :prixMin AND :prixMax')
//
//            ->setParameters(array(
//
//                'anneeProductionMin' => $data['annee_Production'],
//
//                'anneeProductionMax' => $data['annee_Production_Max'],
//
//                'kilometresMin' => $data['kilometres'],
//
//                'kilometresMax' => $data['kilometres_Max'],
//
//                'prixMin' => $data['prix'],
//
//                'prixMax' => $data['prix_Max']));
//
//
//
//        return $query->getQuery()->getResult();
//
//    }

}
