<?php

namespace AppBundle\Repository;

/**
 * ServiceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceCategoryRepository extends \Doctrine\ORM\EntityRepository
{

// Depuis le repository d'Advert
    public function getServiceCategoriesWithProviders()
    {
        $qb = $this
            ->createQueryBuilder('sc')
            ->leftJoin('sc.providers', 'prov')
            ->addSelect('prov')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
