<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TempUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempUserRepository extends EntityRepository
{
    public function findOneByToken($token){

        $qb = $this->createQueryBuilder('tempUser');

        $qb
            ->where('tempUser.token = :token')
            ->setParameter('token',$token)
        ;

        return $qb
            ->getQuery()
            ->getSingleResult();

    }
}
