<?php

namespace AppBundle\Repository;

/**
 * TempUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TempUserRepository extends \Doctrine\ORM\EntityRepository
{
}
