<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findOneById($id){

        $qb = $this->createQueryBuilder('user');

        $qb
            ->where('user.id = :id')
            ->setParameter('id',$id)
        ;

        return $qb
            ->getQuery()
            ->getSingleResult();

    }
}
