# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

#    encoders:
#        bCript ....

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            # si je commente ceci je n ai plus access a mes assets
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main: #main est le nom arbitraire du firewall
            # securiser l'entierete de mon app
            pattern: ^/
            anonymous: ~
#            http_basic: ~

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

#    access_control:
#      - { path: ^/example-route-admin, roles: ROLE_ADMIN}