# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_users:
          entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            # si je commente ceci je n ai plus access a mes assets
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #main est le nom arbitraire du firewall
        main:
            # securiser l'entierete de mon app
            # pattern: ^/
            anonymous: ~
            guard:
              authenticators:
                - app.security.login_form_authenticator

            logout:
              path: /logout
              # activate different ways to authenticate

              # http_basic: ~
              # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

              # form_login: ~
              # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
        - { path: ^/admin, roles: ROLE_USER }

#    access_control:
#      - { path: ^/example-route-admin, roles: ROLE_ADMIN}