# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
        AppBundle\Entity\TempUser:
            algorithm: bcrypt
            cost: 12

#        Symfony\Component\Security\Core\User\User: plaintext

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [in_memory, our_db_provider]
        in_memory:
            memory:
                users:
                    admin@admin.be:
                        password: admin
                        roles: 'ROLE_ADMIN'
        our_db_provider:
            entity:
                class: AppBundle\Entity\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            # si je commente ceci je n ai plus access a mes assets
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #main est le nom arbitraire du firewall
        main:
            # securiser l'entierete de mon app
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
#            http_basic: ~
            provider: our_db_provider
              # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
#            guard:
#              authenticators:
#                - app.security.login_form_authenticator

            logout:
              path: /logout
              target: home
              # activate different ways to authenticate

              # form_login: ~
              # https://symfony.com/doc/current/security/form_login_setup.html

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
#        - { path: ^/admin, roles: ROLE_ADMIN }
#- { path: ^/, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
#    access_control:
#      - { path: ^/example-route-admin, roles: ROLE_ADMIN}